# Generated by Django 5.2.11 on 2026-02-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_method', models.CharField(help_text='Preferred method of contact (e.g., Email, Phone)', max_length=100)),
                ('project_description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
